version: 2.5.0
services:
    app:
      image: node:16-alpine
      command: sh -c "npm install && npm run start"
      ports:
        - 8000:8000
      working_dir: /app
      volumes:
        - ./:/app
      environment:
        DB_HOST: localhost
        DB_PORT: 3306
        DB_USERNAME: root
        DB_PASSWORD: 1234
        DB_DATABASE: hiepvd
    mysql:
      image: mysql:8.0
      volumes:
        - todo-mysql-data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: todos
volumes:
  todo-mysql-data:
    