version: 2.5.0
services:
    app:
      image: node:16-alpine
      command: sh -c "npm install && npm run start"
      ports:
        - 8000:8000
      working_dir: /app
      volumes:
        - ./:/app
      environment:
        MYSQL_HOST: mysql
        MYSQL_USER: root
        MYSQL_PASSWORD: secret
        MYSQL_DB: todos
      networks:
        my-network:
    mysql:
      image: mysql:8.0.32
      ports:
        - 3306:3306
      volumes:
        - todo-mysql-data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: todos
      networks:
        my-network:
volumes:
  todo-mysql-data:
networks:
  my-network:
    