# version: 2.5.0
services:
    app:
      image: node:16-alpine
      command: sh -c "npm install && npm run start"
      ports:
        - 8000:8000
        - 8001:8001
      working_dir: /app
      volumes:
        - ./:/app
      environment:
        MYSQL_HOST: ${DB_HOST}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_DB: ${DB_DATABASE}
      networks:
        my-network:

    # websocket:
    #   build: .
    #   ports:
    #     - '8001:8001'
    #   depends_on:
    #     - app
    #   networks:
    #     my-network:

    mysql:
      image: mysql:8.0.32
      ports:
        - 3307:3306
      volumes:
        - todo-mysql-data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
      networks:
        my-network:
volumes:
  todo-mysql-data:
networks:
  my-network:
    